name: Manually Release
on: 
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}
          NPM_AUTH_TOKEN: ${{ secrets.TOKEN_FOR_NPM }}
              
