name: Manually Release
on: 
  workflow_dispatch:
    inputs:
      skip-bump:
        type: boolean
        description: Skip Publish
      skip-docs:
        type: boolean
        description: Skip Publish

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup
        run: npm ci  
      - name: Bump And Release
        uses: ./
        with:
          git-user-email: 'bvkimball@users.noreply.github.com'
          skip-bump: ${{ github.event.inputs.skip-bump }}
          skip-docs: ${{ github.event.inputs.skip-docs }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}
          NPM_AUTH_TOKEN: ${{ secrets.TOKEN_FOR_NPM }}
              
