name: Manually Release
on: 
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          git config --local user.email "bvkimball@users.noreply.github.com"
          git config --local user.name "Bump And Release"
          npm ci  
      - name: Bump And Release
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}
          NPM_AUTH_TOKEN: ${{ secrets.TOKEN_FOR_NPM }}
              
